services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT} 
      - NODE_ENV=production
      - DATABASE_URL=mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - technical
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/v0/health']
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    env_file:
      - .env
    image: mysql:lts
    container_name: app_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT_INTERN}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --skip-log-bin --innodb-buffer-pool-size=64M
    volumes:
      - mysql-db:/var/lib/mysql
      - ./scripts/mysql:/scripts:ro
    networks:
      - technical
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  database_data:

networks:
  technical:
    driver: bridge
