version: '3'

services:
  mysql:
    env_file:
      - .env
    image: mysql:lts
    container_name: app_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT_INTERN}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --skip-log-bin --innodb-buffer-pool-size=64M
    volumes:
      - mysql-db:/var/lib/mysql
      - ./scripts/mysql:/scripts:ro
    networks:
      - technical
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 3

  # redis:
  #   image: redis:alpine
  #   container_name: app_redis
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - technical
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: unless-stopped

volumes:
  database_data:
  # redis_data:

networks:
  technical:
    driver: bridge
