
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CUSTOMER_PROFILE_REPOSITORY = 'CUSTOMER_PROFILE_REPOSITORY';
export const WORKER_PROFILE_REPOSITORY = 'WORKER_PROFILE_REPOSITORY';
export const SHOP_REPOSITORY = 'SHOP_REPOSITORY';
export const SHOP_WORKER_REPOSITORY = 'SHOP_WORKER_REPOSITORY';
